eureka:
    instance:
        leaseRenewalIntervalInSeconds:10
    client:
        serviceUrl:
            defaultZone: http://localhost:8762/v2/

miguel:
  test: hello world, from Bitbucket!!!

hystrix:
    dashboard:
        serviceName: zinco-turbine
        clusterName: ZincoGroup

zuul:
    proxy:
        route:
            customer: /api1
            tenant: /api2
            device: /api3
