eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/

hls-microservice:
    hlsKey: key2
    
hystrix:
    dashboard:
        serviceName: quickplay-turbine
        clusterName: quickplayGroup


         
bookmark-microservice:
         databaseServiceName: http://database-microservice

creditcard-microservice:
    braintree:
         environment: sandbox
         merchantId: ddd44gynpmzcw45f
         publicKey: b4vn98989c7xs7dn
         privateKey: b197ffecb8077b6932fc3c69ef11f91a
         databaseServiceName: http://database-microservice

customer-microservice:
         databaseServiceName: http://database-microservice

device-microservice:
         databaseServiceName: http://database-microservice

entitlement-microservice:
         databaseServiceName: http://database-microservice

genre-microservice:
         databaseServiceName: http://database-microservice

hls-microservice:
         databaseServiceName: http://database-microservice

offer-microservice:
         databaseServiceName: http://database-microservice
         

         
playback-microservice:
         databaseServiceName: http://database-microservice

product-microservice:
         solrReadUrl: http://localhost:8983/solr/select
         solrWriteUrl: http://localhost:8983/solr/update
         defaultSearcheableFields: title,id,directors,producers,genres,shorttitle,actors,producttype,releaseyear
         defaultQueryTemplate: title:{}  OR directors:{} OR shorttitle:{} OR producers:{} 
         databaseServiceName: http://database-microservice
         tenantServiceName: http://tenant-microservice
         offerServiceName: http://offer-microservice

promotion-microservice:
         databaseServiceName: http://database-microservice        

         
         
purchase-microservice:
         solrReadUrl: http://localhost:8983/solr/select
         databaseServiceName: http://database-microservice
         tenantServiceName: http://tenant-microservice
         offerServiceName: http://offer-microservice
         braintree: 
                environment: sandbox
                merchantId: ddd44gynpmzcw45f
                publicKey: b4vn98989c7xs7dn
                privateKey: b197ffecb8077b6932fc3c69ef11f91a
         
rating-microservice:
         databaseServiceName: http://database-microservice
         
review-microservice:
         databaseServiceName: http://database-microservice
         
rotten-tomatoes-microservice:
        applicationName: LibertasQP
        applicationKey: nwwhgh8hhtfvu77u85s25nc8
        databaseServiceName: http://database-microservice
        solrReadUrl: http://localhost:8983/solr/select
        searchQueryUrlTemplate: http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey=${apiKey}&q=${searchTerm}&page_limit=1
        similarQueryUrlTemplate: http://api.rottentomatoes.com/api/public/v1.0/movies/${rottenTomatoesProductId}/similar.json?apikey=${apiKey}
        
tenant-microservice:
         databaseServiceName: http://database-microservice
    
watchhistory-microservice:
         databaseServiceName: http://database-microservice
         
workflow-microservice:
         databaseServiceName: http://database-microservice
zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
