zinco-eureka:
    instance:
        leaseRenewalIntervalInSeconds:10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/


zinco-hystrix:
    dashboard:
        serviceName: zinco-turbine
        clusterName: ZincoGroup

zinco-zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
