eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/

hls-microservice:
    hlsKey: key2
    
hystrix:
    dashboard:
        serviceName: quickplay-turbine
        clusterName: quickplayGroup

product-microservice:
    solr:
         readUrl: localhost:8983/solr
         writeUrl: localhost:8983/solr
         
creditcard-microservice:
    braintree:
         environment: sandbox
         merchantId: ddd44gynpmzcw45f
         publicKey: b4vn98989c7xs7dn
         privateKey: b197ffecb8077b6932fc3c69ef11f91a

zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
