eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/

hls-microservice:
    hlsKey: key2
    
hystrix:
    dashboard:
        serviceName: quickplay-turbine
        clusterName: quickplayGroup


         
bookmark-microservice:
         databaseServiceName: database-microservice

creditcard-microservice:
    braintree:
         environment: sandbox
         merchantId: ddd44gynpmzcw45f
         publicKey: b4vn98989c7xs7dn
         privateKey: b197ffecb8077b6932fc3c69ef11f91a
         databaseServiceName: database-microservice

customer-microservice:
         databaseServiceName: database-microservice

device-microservice:
         databaseServiceName: database-microservice

entitlement-microservice:
         databaseServiceName: database-microservice

genre-microservice:
         databaseServiceName: database-microservice

hls-microservice:
         databaseServiceName: database-microservice

offer-microservice:
         databaseServiceName: database-microservice


         
playback-microservice:
         databaseServiceName: database-microservice

product-microservice:
         readUrl: http://localhost:8983/solr/select
         writeUrl: http://localhost:8983/solr/update
         defaultSearcheableFields: title,id,directors,producers,genres,shorttitle,actors,producttype,releaseyear
         defaultQueryTemplate: title:{}  OR directors:{} OR shorttitle:{} OR producers:{} 
         databaseServiceName: database-microservice
         tenantServiceName: tenant-microservice

promotion-microservice:
         databaseServiceName: database-microservice        

         
         
purchase-microservice:
         databaseServiceName: database-microservice
         
         
         
rating-microservice:
         databaseServiceName: database-microservice
         
review-microservice:
         databaseServiceName: database-microservice
         
tenant-microservice:
         databaseServiceName: http://database-microservice
    
watchhistory-microservice:
         databaseServiceName: database-microservice
         
workflow-microservice:
         databaseServiceName: database-microservice
zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
