eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/

hls-microservice:
    hlsKey: key2
    
hystrix:
    dashboard:
        serviceName: quickplay-turbine
        clusterName: quickplayGroup


         
bookmark-microservice:
         databaseServiceName: database-microservervice

creditcard-microservice:
    braintree:
         environment: sandbox
         merchantId: ddd44gynpmzcw45f
         publicKey: b4vn98989c7xs7dn
         privateKey: b197ffecb8077b6932fc3c69ef11f91a
         databaseServiceName: database-microservervice

customer-microservice:
         databaseServiceName: database-microservervice

device-microservice:
         databaseServiceName: database-microservervice

entitlement-microservice:
         databaseServiceName: database-microservervice

genre-microservice:
         databaseServiceName: database-microservervice

hls-microservice:
         databaseServiceName: database-microservervice

offer-microservice:
         databaseServiceName: database-microservervice


         
playback-microservice:
         databaseServiceName: database-microservervice

product-microservice:
         readUrl: http://localhost:8983/solr/select
         writeUrl: http://localhost:8983/solr/update
         defaultSearcheableFields: title,id,directors,producers,genres,shorttitle,actors,producttype,releaseyear
         defaultQueryTemplate: title:{}  OR directors:{} OR shorttitle:{} OR producers:{} 
         databaseServiceName: database-microservervice
         tenantServiceName: tenant-microservervice

promotion-microservice:
         databaseServiceName: database-microservervice        

         
         
purchase-microservice:
         databaseServiceName: database-microservervice
         
         
         
rating-microservice:
         databaseServiceName: database-microservervice
         
review-microservice:
         databaseServiceName: database-microservervice
         
tenant-microservice:
         databaseServiceName: http://database-microservervice
    
watchhistory-microservice:
         databaseServiceName: database-microservervice
         
workflow-microservice:
         databaseServiceName: database-microservervice
zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
