eureka:
    instance:
        leaseRenewalIntervalInSeconds:10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/

miguel:
  test: hello world, from Bitbucket!!!

hystrix:
    dashboard:
        serviceName: zinco-turbine
        clusterName: ZincoGroup

zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
