eureka:
    instance:
        leaseRenewalIntervalInSeconds:10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/v2/


hystrix:
    dashboard:
        serviceName: customer-microservice
        clusterName: zincoGroup

zuul:
    proxy:
        route:
            customer-microservice: /customer
            tenant-microservice: /tenant
            device-microservice: /device
